/*
NES模拟器使用C++实现
*/

void test_asl();
void test_adc();
void test_and();
void test_bcc();
void test_bcs();
void test_beq();
void test_bit();
void test_bmi();
void test_bne();
void test_bpl();
void test_brk();
void test_bvc();
void test_bvs();
void test_clc();
void test_cld();
void test_cli();
void test_clv();
void test_cmp();
void test_cpx();
void test_cpy();
void test_dec();
void test_dex();
void test_dey();
void test_eor();
void test_inc();
void test_inx();
void test_iny();
void test_jmp();
void test_jsr();
void test_lda();
void test_ldx();
void test_ldy();
void test_lsr();
void test_nop();
void test_ora();
void test_pha();
void test_php();
void test_pla();
void test_plp();
void test_rol();
void test_ror();
void test_rti();
void test_rts();
void test_sbc();
void test_sec();
void test_sed();
void test_sei();
void test_sta();
void test_stx();
void test_sty();
void test_tax();
void test_tay();

int main()
{
    test_adc();
    test_asl();
    test_and();
    test_bcc();
    test_bcs();
    test_beq();
    test_bit();
    test_bmi();
    test_bne();
    test_bpl();
    test_brk();
    test_bvc();
    test_bvs();
    test_clc();
    // todo: 增加op码和助记符的测试文件
    test_cld();
    test_cli();
    test_clv();
    test_cmp();
    test_cpx();
    test_cpy();
    test_dec();
    test_dex();
    test_dey();
    test_eor();
    test_inc();
    test_inx();
    test_iny();
    test_jmp();
    test_jsr();
    test_lda();
    test_ldx();
    test_ldy();
    test_lsr();
    test_nop();
    test_ora();
    test_pha();
    test_php();
    test_pla();
    test_plp();
    test_rol();
    test_ror();
    test_rti();
    test_rts();
    test_sbc();
    test_sec();
    test_sed();
    test_sei();
    test_sta();
    test_stx();
    test_sty();
    test_tax();
    test_tay();
}
